apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: fluidai-demo
type: Opaque
stringData:
  DATABASE_URL: "PLACEHOLDER"
  REDIS_URL: "redis://redis:6379/0"
  POSTGRES_PASSWORD: "PLACEHOLDER"
  POSTGRES_USER: "PLACEHOLDER"
  POSTGRES_DB: "PLACEHOLDER"
